name: Deploy via ftp
on:
  push:
    tags:
      - '*'  
    branches:
    - 'main'
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Install .NET Wasm Tools
      run: dotnet workload install wasm-tools

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Publish
      run: dotnet publish FlexPro.Client.csproj -c:Release -o docs --nologo

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ secrets.HOST }} 
        user: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        localDir: "docs/wwwroot"
